### ISSUE TITLE
Remove 1px border-bottom on navbar child items

### ISSUE THREAD

**Issue by allanaaa** [omeka/theme-minimalist#12]
![minimalistborderbottom](https://user-images.githubusercontent.com/28012148/228956570-a0910963-2bd6-4b3a-aa96-bb80a51eb525.PNG)

Child links in the navbar has a 1px border-bottom that doesn't change on hover, so it looks weird in the last (or only) child. I'd remove it (not sure that it's needed), or change its colour on hover too.

```
#top-nav .sub-nav.open li a {
  color: #684B98;
  padding: 1em;
>>> border-bottom: 1px solid white;
}

#top-nav .nav-menu .sub-nav.open li a:hover {
    background-color: #cf9ad9;
    color: white;
  }

```

**Comment by kimisgold** [comment]
Fixed and ready for a look.
