### ISSUE TITLE
with-advanced class is always added

### ISSUE THREAD

**Issue by smth** [omeka/theme-minimalist#5]
The `with-advanced` [class](https://github.com/omeka/theme-minimalist/blob/01a1843d6564d1f88be3743d63508881a915121f/javascripts/globals.js#L10) is used to make room for the advanced button, however it appears to be added regardless of whether advanced search is enabled.

**Comment by kimisgold** [comment]
Fixed in dc613a41604d2ff97d70876c4b09b0a704ba73d9.
